version = '1.0.0'

[general]
log_level = 'info'
color = true

[changelog]
style = 'conventional'
template = 'templates/changelog.md'
sort = true
jira_integration = false
tag_filter_pattern = ''
path = 'CHANGELOG.md'
no_case = false

[changelog.info]
title = ''
repository_url = ''

[changelog.options]
[changelog.options.commits]
sort_by = 'scope'

[changelog.options.commits.filters]

[changelog.options.commit_groups]
group_by = 'type'
sort_by = 'title'

[changelog.options.commit_groups.title_maps]
build = 'Build System'
ci = 'Continuous Integration'
docs = 'Documentation'
feat = 'Features'
fix = 'Bug Fixes'
perf = 'Performance Improvements'
refactor = 'Code Refactoring'
test = 'Tests'

[changelog.options.header]
pattern = '^(\w*)(?:\(([\w\$\.\-\*\s]*)\))?\:\s(.*)$'

[[changelog.options.header.pattern_maps]]
pattern = '^(\w*)(?:\(([\w\$\.\-\*\s]*)\))?\:\s(.*)$'

[changelog.options.notes]
keywords = ['BREAKING CHANGE', 'DEPRECATED']

[changelog.jira]
url = ''
base_url = ''
username = ''
api_key = ''
project_key = ''
issue_pattern = '([A-Z]+-\d+)'

[ai]
enable = true
provider = 'mistral'
model = 'mistral-medium'
api_key = ''
api_url = ''
api_custom_headers = ''
tokens_max_input = 4096
tokens_max_output = 500
