version = '1.0.0'

[ai]
default_model = 'mistral-medium'
default_provider = 'mistral'
enable = true
verbose = false

[ai.models]
[ai.models.gpt-3]
context_window = 0
max_tokens = 0
model_id = ''
provider = ''
stream_response = false
temperature = 0.0
top_p = 0.0

[ai.models.gpt-3.5-turbo]
context_window = 4096
max_tokens = 1024
model_id = 'gpt-3.5-turbo'
provider = 'openai'
stream_response = false
temperature = 0.7
top_p = 0.9

[ai.models.gpt-4]
context_window = 8192
max_tokens = 1024
model_id = 'gpt-4'
provider = 'openai'
stream_response = false
temperature = 0.7
top_p = 0.9

[ai.models.mistral-medium]
context_window = 8192
max_tokens = 1024
model_id = 'mistral-medium'
provider = 'mistral'
stream_response = false
temperature = 0.7
top_p = 0.9

[ai.models.mistral-small]
context_window = 8192
max_tokens = 1024
model_id = 'mistral-small'
provider = 'mistral'
stream_response = false
temperature = 0.7
top_p = 0.9

[changelog]
jira_integration = false
no_case = false
path = ''
sort = 'semver'
style = 'github'
tag_filter_pattern = 'v*'
template = 'CHANGELOG.tpl.md'

[changelog.jira]
base_url = ''
issue_pattern = '[A-Z]+-[0-9]+'
project_key = ''
username = ''

[general]
color = true
log_level = 'info'
