version = '1.0.0'

[general]
log_level = 'info'

[ai]
enable = true
provider = 'mistral'
model = 'mistral-medium'
api_key = ''
api_url = ''
api_custom_headers = ''
tokens_max_input = 4096
tokens_max_output = 500
