FROM ghcr.io/clikd-inc/gate:1.0.0 AS gate
FROM ghcr.io/clikd-inc/rig:0.5.0 AS rig
FROM ghcr.io/clikd-inc/studio:0.5.0 AS studio
FROM ghcr.io/clikd-inc/postgres:18.0 AS postgres
FROM ghcr.io/clikd-inc/keydb:6.3.4 AS keydb
FROM ghcr.io/clikd-inc/scylladb:2025.1.9 AS scylladb
FROM ghcr.io/clikd-inc/minio:2025.10.15 AS minio
FROM ghcr.io/clikd-inc/nats:2.12.1 AS nats
FROM ghcr.io/clikd-inc/apisix:3.11.0 AS apisix
