name: Changelog Generation

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:  # Ermöglicht manuelle Ausführung

jobs:
  generate-changelog:
    name: Generate Changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Vollständiger Checkout für Git-bezogene Operationen

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: true

      - name: Install dependencies
        run: go mod download

      - name: Build clikd
        run: go build -o clikd-temp ./cmd/clikd

      - name: Generate Changelog
        run: |
          ./clikd-temp changelog --style github > CHANGELOG.md
          
      - name: Check for changes
        id: check_changes
        run: |
          if git diff --quiet CHANGELOG.md; then
            echo "No changes to CHANGELOG.md"
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected in CHANGELOG.md"
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add CHANGELOG.md
          git commit -m "docs: Update CHANGELOG.md [skip ci]"
          git push 
